/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*    This file is part of the code gasa01, which contains code              */
/*    for Project A01                                                        */
/*    "Global Methods for Stationary and Instationary Gastransport"          */
/*    of the SFB/TRR 154 "Mathematical Modelling, Simulation and             */
/*    Optimization on the Example of Gas Networks".                          */
/*                                                                           */
/*    Copyright (C) 2015-     Discrete Optimization Group, TU Darmstadt      */
/*                                                                           */
/*    Based on SCIP  --- Solving Constraint Integer Programs                 */
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/**@file   disp_gradient.h
 * @ingroup DISPLAYS
 * @brief  Column to display the number of gradient cuts generated by cons_ode
 * @author Marc Pfetsch
 */

#ifndef __SCIP_DISP_GRADIENT_H__
#define __SCIP_DISP_GRADIENT_H__

#include "scip/scip.h"

#ifdef __cplusplus
extern "C" {
#endif

/** creates the gradient display column and includes it in SCIP */
SCIP_EXPORT
SCIP_RETCODE SCIPincludeDispGradient(
   SCIP*                 scip                /**< SCIP data structure */
   );

#ifdef __cplusplus
}
#endif

#endif
