/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*    This file is part of the code gasa01, which contains code              */
/*    for Project A01                                                        */
/*    "Global Methods for Stationary and Instationary Gastransport"          */
/*    of the SFB/TRR 154 "Mathematical Modelling, Simulation and             */
/*    Optimization on the Example of Gas Networks".                          */
/*                                                                           */
/*    Copyright (C) 2015-     Discrete Optimization Group, TU Darmstadt      */
/*                                                                           */
/*    Based on SCIP  --- Solving Constraint Integer Programs                 */
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/**@file   disp_gradient.c
 * @brief  Column to display the number of gradient cuts generated by cons_ode
 * @author Marc Pfetsch
 */

#include <assert.h>

#include "disp_gradient.h"
#include "cons_pipe_ode.h"

#define DISP_NAME             "gradient"
#define DISP_DESC             "number of gradient cuts"
#define DISP_HEADER           "gradcuts"
#define DISP_WIDTH            8              /**< the width of the display column */
#define DISP_PRIORITY         30001          /**< the priority of the display column */
#define DISP_POSITION         3501           /**< the relative position of the display column */
#define DISP_STRIPLINE        TRUE           /**< default for displaying column separated with a line from its right neighbor */


/*
 * Data structures
 */

/** display column data */
struct SCIP_DispData
{
   SCIP_CONSHDLR*        conshdlrPipeODE;    /**< pointer to the pipe ODE constraint handler */
};



/*
 * Callback methods of display column
 */

/** copy method for dialog plugins (called when SCIP copies plugins) */
static
SCIP_DECL_DISPCOPY(dispCopyGradient)
{  /*lint --e{715}*/
   assert( scip != NULL );
   assert( disp != NULL );

   /* call inclusion method of dialog */
   SCIP_CALL( SCIPincludeDispGradient(scip) );

   return SCIP_OKAY;
}

/** destructor of display column to free user data (called when SCIP is exiting) */
static
SCIP_DECL_DISPFREE(dispFreeGradient)
{
   SCIP_DISPDATA* dispdata;

   assert( scip != NULL );
   assert( disp != NULL );
   dispdata = SCIPdispGetData(disp);
   assert( dispdata != NULL );

   SCIPfreeMemory(scip, &dispdata);
   SCIPdispSetData(disp, NULL);

   return SCIP_OKAY;
}

/** solving process initialization method of display column (called when branch and bound process is about to begin) */
static
SCIP_DECL_DISPINITSOL(dispInitsolGradient)
{  /*lint --e{715}*/
   SCIP_DISPDATA* dispdata;

   assert( disp != NULL );
   dispdata = SCIPdispGetData(disp);
   assert( dispdata != NULL );

   dispdata->conshdlrPipeODE = SCIPfindConshdlr(scip, "pipe_ode");
   if ( dispdata->conshdlrPipeODE == NULL )
      return SCIP_OKAY;

   return SCIP_OKAY;
}

/** output method of display column to output file stream 'file' */
static
SCIP_DECL_DISPOUTPUT(dispOutputGradient)
{  /*lint --e{715}*/
   SCIP_DISPDATA* dispdata;

   assert( scip != NULL );
   assert( disp != NULL );

   dispdata = SCIPdispGetData(disp);

   assert( dispdata != NULL );
   if ( dispdata->conshdlrPipeODE == NULL )
      return SCIP_OKAY;

   SCIPdispLongint(SCIPgetMessagehdlr(scip), file, (long long) SCIPconsPipeODEGetNGradientCuts(dispdata->conshdlrPipeODE), DISP_WIDTH);

   return SCIP_OKAY;
}


/*
 * display column specific interface methods
 */

/** creates the SDP-iterations display column and includes it in SCIP */
SCIP_RETCODE SCIPincludeDispGradient(
   SCIP*                 scip                /**< SCIP data structure */
   )
{
   SCIP_DISPDATA* dispdata = NULL;

   assert( scip != NULL );

   /* create display column data */
   SCIP_CALL( SCIPallocMemory(scip, &dispdata) );
   dispdata->conshdlrPipeODE = NULL;

   /* include display column */
   SCIP_CALL( SCIPincludeDisp(scip, DISP_NAME, DISP_DESC, DISP_HEADER, SCIP_DISPSTATUS_AUTO,
         dispCopyGradient, dispFreeGradient, NULL, NULL, dispInitsolGradient, NULL, dispOutputGradient,
         dispdata, DISP_WIDTH, DISP_PRIORITY, DISP_POSITION, DISP_STRIPLINE) );

   return SCIP_OKAY;
}
