#* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
#*                                                                           *
#*    This file is part of the code gasa01, which contains code              *
#*    for Project A01 "Global Methods for Stationary Gastransport"           *
#*    of the SFB#TRR 154 "Mathematical Modelling, Simulation and             *
#*    Optimization on the Example of Gas Networks".                          *
#*                                                                           *
#*    Copyright (C) 2015-     Discrete Optimization Group, TU Darmstadt      *
#*                                                                           *
#*    Based on SCIP  --- Solving Constraint Integer Programs                 *
#*                                                                           *
#* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
target:
	cd .. && $(MAKE) $(MAKECMDGOALS)
%:
	cd .. && $(MAKE) $(MAKECMDGOALS)
